import React from "react";
import "../styles/Results.css";

export default function RiskAssessment({ data }) {
  if (!data || !data.risk) {
    return <div className="page-container">No risk data available</div>;
  }

  const { score, risk_level } = data.risk;
  
  const getRiskColor = (level) => {
    switch (level) {
      case "Low Risk":
        return "#27ae60";
      case "Medium Risk":
        return "#f39c12";
      case "High Risk":
        return "#e74c3c";
      default:
        return "#95a5a6";
    }
  };

  const getRiskRecommendation = (level) => {
    switch (level) {
      case "Low Risk":
        return "Recommended for approval - Strong financial profile";
      case "Medium Risk":
        return "Conditional approval - Further review recommended";
      case "High Risk":
        return "Not recommended - High risk profile";
      default:
        return "Review required";
    }
  };

  return (
    <div className="page-container">
      <h1>Risk Assessment</h1>

      <div className="risk-container">
        <div className="risk-score-box">
          <div className="score-display" style={{ borderColor: getRiskColor(risk_level) }}>
            <div className="score-number">{score}</div>
            <div className="score-label">Risk Score</div>
          </div>
        </div>

        <div className="risk-level-box" style={{ borderLeftColor: getRiskColor(risk_level) }}>
          <h2 style={{ color: getRiskColor(risk_level) }}>{risk_level}</h2>
          <p className="recommendation">{getRiskRecommendation(risk_level)}</p>
          {/* Show LLM-based risk summary if present */}
          {data.risk_summary && (
            <div className="risk-summary-box" style={{ marginTop: 16, background: "#f8f9fa", padding: 16, borderRadius: 8, border: "1px solid #e1e4e8" }}>
              <h4 style={{ margin: 0, color: "#003d82" }}>AI Risk Summary</h4>
              <p style={{ margin: 0 }}>{data.risk_summary}</p>
            </div>
          )}
        </div>
      </div>

      <div className="risk-meter">
        <div className="meter-bar">
          <div
            className="meter-fill"
            style={{
              width: `${score}%`,
              backgroundColor: getRiskColor(risk_level),
            }}
          ></div>
        </div>
        <div className="meter-labels">
          <span>Low Risk</span>
          <span>Medium Risk</span>
          <span>High Risk</span>
        </div>
      </div>

      <div className="risk-factors">
        <h3>Risk Factors Considered</h3>
        <ul>
          <li>Financial stability and profitability</li>
          <li>Debt levels and leverage ratios</li>
          <li>Market sentiment and news analysis</li>
          <li>Industry trends and external factors</li>
        </ul>
      </div>

      <div className="decision-box" style={{ borderLeftColor: getRiskColor(risk_level) }}>
        <h3>Recommendation</h3>
        <p>{getRiskRecommendation(risk_level)}</p>
        <p style={{ fontSize: "12px", marginTop: "10px", color: "#666" }}>
          This assessment is generated by AI and should be reviewed by qualified credit officers before final decision.
        </p>
      </div>
    </div>
  );
}
